Adding Active Monitoring Questionnaires
tewhatuora/cinc-fhir-ig pull request #51
Opened 2023-08-14 23:35 UTC by camrichards

This PR is to add the profiles for the following 2 questionnaires to the IG.

[https://mohits.atlassian.net/wiki/spaces/CVIP/pages/3514630175/Survey+contents+-+Day+7+-+Influenza](https://www.google.com/url?q=https://mohits.atlassian.net/wiki/spaces/CVIP/pages/3514630175/Survey%2Bcontents%2B-%2BDay%2B7%2B-%2BInfluenza&source=gmail-imap&ust=1691452428000000&usg=AOvVaw0pMtbRD2l3mcU58uMqRQZr)

[https://mohits.atlassian.net/wiki/spaces/CVIP/pages/3514663033/Survey+contents+-+Day+42+-+Influenza](https://www.google.com/url?q=https://mohits.atlassian.net/wiki/spaces/CVIP/pages/3514663033/Survey%2Bcontents%2B-%2BDay%2B42%2B-%2BInfluenza&source=gmail-imap&ust=1691452428000000&usg=AOvVaw2dKfSP8RiZAAoiJd21uI8Q)

2023-08-16 01:03 UTC, swithinfoote requested changes

2023-08-18 05:44 UTC, camrichards commented on input/fsh/canonical/ActiveMonitoringDay42SurveyQuestionnaire.fsh
> +* item[=].item[=].answerOption[+].valueCoding = $sct#193093009 "Bell’s palsy"
not according to snomed

2023-08-18 05:44 UTC, camrichards commented
All changes made in latest commit

2023-08-23 22:09 UTC, swithinfoote approved these changes

2023-08-23 22:09 UTC, merged