Feature/tiji jose cms
tewhatuora/cinc-fhir-ig pull request #94
Opened 2024-09-24 01:09 UTC by tijijose

add Communication Profile in test

2024-09-24 06:36 UTC, swithinfoote commented
In order to support the campaign I think you need a codeset (unless I have misunderstood the intent) - e.g.
```
CodeSystem: CommunicationCampaignTypes
Id: hnz-communication-campaign-type-codes
Title: "Codes for Campaigns"
Description:  "Each code represents a campaign type"
* #C2141acc05fdf4bc79070e472e69b17f6 "Measles HealthCheck Journey"
* #SOMEOTHERCODE "Some other value"
* ^publisher = "Health New Zealand | Te Whatu Ora"
* ^experimental = false
* ^caseSensitive = false
* ^purpose = "Enables a specific communication to be tied to a campaign."
* ^status = #active

ValueSet: CommunicationCampaignTypesValueSet
Id: hnz-communication-campaign-type-valueset
Title: "Valueset for Campaigns"
Description:  "Valueset for Campaigns"
* ^publisher = "Health New Zealand | Te Whatu Ora"
* ^version = "1.0.0"
* ^experimental = false
* ^status = #active
* include codes from system hnz-communication-campaign-type-codes
```

2024-09-30 01:08 UTC, swithinfoote requested changes

2024-09-30 01:58 UTC, tijijose commented on input/fsh/extensions/CommunicationExtensions.fsh
> +* value[x] only Coding
it is value string. These are random generated codes and description from cpir side.If we use codeset then it will be difficult to maintain

2024-09-30 02:05 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +* extension[=].valueContactPoint.system = #sms
changed as adviced:
* extension[0].url = Canonical(hnz-Contact-point-extension-id)
* extension[=].valueContactPoint.system = #SMSWRIT
* extension[=].valueContactPoint.value = "555-1234"

2024-09-30 02:07 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +Instance : CommunicationSMSexample
does this ok,
Instance : SMSCommunicationexample
InstanceOf : CPIRCommunication

2024-09-30 02:09 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +* identifier[0].use = #usual
system added as advised,

* identifier[0].use = #usual
* identifier[0].value = "#ebdb8d66-1390-42c7-89a6-a9a75d65d0e6"
* identifier[0].system = "https://standards.digital.health.nz/ns/nhi-id"

2024-09-30 02:13 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +* extension[=].valueString = "Measles_HealthCheck_Email_Journey_Sit_24_Feb"
As adviced, Both are valueString now.These are AWS generated random IDs
extension[+].url = Canonical(hnz-campaign-code-extension)
* extension[=].valueString = "2141acc05fdf4bc79070e472e69b17f6"
* extension[+].url = Canonical(hnz-campaign-name-extension)
* extension[=].valueString = "Measles_HealthCheck_Email_Journey_Sit_24_Feb"

2024-09-30 03:11 UTC, tijijose commented on input/fsh/capabilities/capabilitystatement.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Communication-​subject"
removed-may be copy paste

2024-09-30 03:11 UTC, tijijose commented on input/fsh/capabilities/capabilitystatement.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Communication-​recipient"
removed-may be copy paste

2024-09-30 19:36 UTC, tijijose commented on input/fsh/terminology/CommunicationStatusValueSet.fsh
> +Id: hnz-communication-delivery-Status-valueset
this is for communication.status.
Current systems are using three codes now that are Delivered, Send,received .These  codes are not matching with FHIR standered required codes (preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error).

2024-10-01 00:44 UTC, tijijose commented on input/fsh/profiles/communication.fsh
> +* status from https://fhir-ig.digital.health.nz/shared-care/ValueSet/hnz-communication-status-codes (required)
extension for hnz-status-codes required

2024-10-01 00:46 UTC, tijijose commented on input/fsh/terminology/CommunicationStatusValueSet.fsh
> +Id: hnz-communication-delivery-Status-valueset
used for  communication.status.

2024-10-01 21:03 UTC, tijijose commented on input/fsh/profiles/communication.fsh
> +* status from https://fhir-ig.digital.health.nz/shared-care/ValueSet/hnz-communication-status-codes (required)
extension for hnz-status-codes 

**codeset**:

CodeSystem: CommunicationDeliveryStatusCodes
Id: hnz-communication-delivery-status-codes
Title: "Codes forCommunicationStatus"
Description:  "Each code represents a communication delivery status"
//* include codes from valueset http://hl7.org/fhir/ValueSet/request-status
* #DELIVERED "Delivered"
* #SEND "Send"
* #RECEIVED "received"
* ^publisher = "Health New Zealand | Te Whatu Ora"
* ^experimental = false
* ^caseSensitive = false
* ^purpose = "Enables a specific  status to be tied to a communication."
* ^status = #active
*
**Valueset**:

ValueSet: CommunicationDeliveryStatusValueSet
Id: hnz-communication-delivery-Status-valueset
Title: "Valueset for Communication Delivery Status"
Description:  "Valueset for Communication Delivery Status "
* ^publisher = "Health New Zealand | Te Whatu Ora"
* ^version = "1.0.0"
* ^experimental = false
* ^status = #active
* include codes from system hnz-communication-delivery-status-codes
* include codes from valueset http://hl7.org/fhir/ValueSet/request-status

2024-10-01 21:06 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +* medium.coding.code = #EMAILWRIT
Yes.,changed to SMSWRIT

2024-10-01 22:09 UTC, tijijose commented on input/fsh/examples/cinc/CommunicationSMSExample.fsh
> +//* basedOn(CommunicationRequest/6777)
No,

2024-10-01 22:30 UTC, tijijose commented on input/fsh/profiles/communication.fsh
> +  hnz-campaign-code-extension named CampaignCode 0..*
added identifier

2024-10-10 22:35 UTC, swithinfoote approved these changes

2024-11-13 22:27 UTC, closed without merging